spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL HOST:localhost}:3306/ecommerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: app
    password: app123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

